### ISSUE TITLE
Add startup/shutdown services

### ISSUE THREAD

**Issue by Nakroma** [nexus-devs/blitz.js#12]
_From @Nakroma on April 28, 2017 14:31_

Add scripts and services that get run on startup or shutdown, sort of like middleware.  
Example:  

`[{ name: "Ensure and create index",
    script: "/scripts/mongo_index.js",
    entry: "start" },
 ... ]`

Makes this issue obsolete / easier to implement: nexus-devs/warframe-nexus#11

_Copied from original issue: nexus-devs/warframe-nexus#13_

**Comment by Kaptard** [comment]
Implemented Hooks. Should fix this issue.
